# Generated by Django 3.2.6 on 2021-08-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_alter_hero_photofilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='PhotoFileName',
            field=models.CharField(max_length=1000000),
        ),
    ]
